swagger: "2.0"
info:
  description: "specification for LOS APIs"
  version: "1.0.0"
  title: "Los project"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v3"
schemes:
- "https"
- "http"
paths:
  /LOS:
    post:
      tags:
      - "LOS"
      summary: "Add a new point"
      description: "Adding a new point"
      operationId: "addPoint"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Point object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/Point"
      responses:
        "405":
          description: "Invalid input"
definitions:
  Point:
    type: "object"
    required:
    - "x"
    - "y"
    - "z"
    properties:
      x:
        type: "integer"
        format: "int64"
      y:
        type: "integer"
        format: "int64"
      z:
        type: "integer"
        format: "int64"        
    xml:
      name: "Point"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"