swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
schemes:
- "https"
- "http"
paths:
  /points/get:
    get:
      tags:
      - "Points"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "getSinglePoint"
      produces:
      - "application/xml"
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "Point"
            items:
              $ref: "#/definitions/Point"
            example:
            - x: 1
              y: 2
              z: 3
            - x: 4
              y: 5
              z: 6
            xml:
              name: points
definitions:
  Point:
    type: "object"
    properties:
      x:
        type: "number"
        format: "float32"
      y:
        type: "number"
        format: "float32"
      z:
        type: "number"
        format: "float32"
    xml:
      name: "Point"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"