#!/usr/bin/env bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

AUTOGENERATED_PATH="$SCRIPT_DIR/AutoGen"
#SPEC_PATH="$SCRIPT_DIR/Assets/StreamingAssets/Spec/simulation.spec"
SPEC_PATH="$SCRIPT_DIR/spec/petstore.yaml"
NAMESPACE="EOSimU.API.AutoGen"
PKG_CTX="v1alpha3"

rm -rf $AUTOGENERATED_PATH/Modules
rm -rf $AUTOGENERATED_PATH/Models
rm -rf $AUTOGENERATED_PATH/Utils

mkdir -p $AUTOGENERATED_PATH
mkdir -p ${SCRIPT_DIR}/tmp_build

java -jar spec/openapi-generator-cli.jar generate \
	-i ${SPEC_PATH} \
	-g csharp-nancyfx \
	-o ${SCRIPT_DIR}/tmp_build \
	--additional-properties=asyncServer=true,packageName=$NAMESPACE,packageContext=$PKG_CTX

# Apply moves
mv ${SCRIPT_DIR}/tmp_build/src/$NAMESPACE/* $AUTOGENERATED_PATH
rm -rf ${SCRIPT_DIR}/tmp_build

# Manual fix for now ...
find "${AUTOGENERATED_PATH}/" -iname "*.cs" | xargs -I {} sed -i 's/return new Response { ContentType = ""};/return new Response { ContentType = null, StatusCode = HttpStatusCode.NoContent };/g' {}

# Manual fix to turn everything into UniTasks
#find "${AUTOGENERATED_PATH}/" -iname "*.cs" | xargs -I {} sed -i "s/\<System.Threading.Tasks\>/Cysharp.Threading.Tasks/g" {}
#find "${AUTOGENERATED_PATH}/" -iname "*.cs" | xargs -I {} sed -i "s/\<Task\>/UniTask/g" {}

# Manual fix to make sure complex types are properly awaited before any operation is performed on them
find "${AUTOGENERATED_PATH}/" -iname "*.cs" | xargs -I {} sed -Ei "s/(await [^\(]*\([^\)]*\))(\..*)/(\1)\2/g" {}

# Manual fix to properly serialize information
find "${AUTOGENERATED_PATH}/Modules/" -iname "*.cs" | xargs -I {} sed -Ei "s/using Cysharp.Threading.Tasks;/using Cysharp.Threading.Tasks;\nusing Newtonsoft.Json;\n/"  {}
find "${AUTOGENERATED_PATH}/Modules/" -iname "*.cs" | xargs -I {} sed -Ei 's/return(.*await .*);/return new Nancy.Responses.TextResponse(contents: JsonConvert.SerializeObject(\1), contentType: "application\/json");/g' {}

# Fix two manual cases of objects
find "${AUTOGENERATED_PATH}/Modules/" -iname "*.cs" | xargs -I {} sed -Ei 's/return new Nancy.Responses.TextResponse\(contents: JsonConvert.SerializeObject\( await service.CameraGetBrowserDebugImage\(Context, entityId\)\), contentType: "application\/json"\)\;/return await service.CameraGetBrowserDebugImage(Context, entityId);/' {}
find "${AUTOGENERATED_PATH}/Modules/" -iname "*.cs" | xargs -I {} sed -Ei 's/return new Nancy.Responses.TextResponse\(contents: JsonConvert.SerializeObject\( await service.CameraGetImageData\(Context, entityId\)\), contentType: "application\/json"\)\;/return await service.CameraGetImageData(Context, entityId);/' {}

# Manual fix for setting bool
find "${AUTOGENERATED_PATH}/" -iname "*.cs" | xargs -I {} sed -i 's/var body = this.Bind<bool?>();/var body = new System.IO.StreamReader(Request.Body).ReadToEnd().ToLower() == "true";/g' {}

# Cleanups
rm -rf "${AUTOGENERATED_PATH}/obj"
rm -rf "${AUTOGENERATED_PATH}/Debug"
rm -rf "${AUTOGENERATED_PATH}/EOSimU.API.AutoGen.nuspec"
#rm -rf "${AUTOGENERATED_PATH}/EOSimU.API.AutoGen.csproj"
rm -rf "${AUTOGENERATED_PATH}/packages.config"
